[source]
type = "N2N"
address = ["Tcp", "localhost:6000"]
magic = "preprod"

[sink]
type = "Terminal"
throttle_min_span_millis = 500
wrap = false


[retries]
max_retries = 3
backoff_unit_sec = 10
backoff_factor = 3
max_backoff_sec = 10
dismissible = true