[source]
type = "N2N"
address = ["Tcp", "localhost:6000"]
magic = "preprod"
min_depth = 1

[[filters]]
type = "Selection"

[filters.check]
predicate = "all_of"

[[filters.check.argument]]
predicate = "variant_in"
argument = ["Transaction"]

[[filters.check.argument]]
predicate = "policy_equals"
argument = "bdc16c0437b25cc7d9addd100cfeb211d8e7fceb14a12c794feca824"

[source.mapper]
include_transaction_details = true


[sink]
type = "Webhook"
url = "http://localhost:3000/oura/"
error_policy = "Continue"


[retries]
max_retries = 3
backoff_unit_sec = 10
backoff_factor = 3
max_backoff_sec = 10
dismissible = true